CREATE TABLE typing_sessions (
	id INTEGER NOT NULL PRIMARY KEY,
	inputs TEXT NOT NULL,
	wpm INTEGER NOT NULL,
	wpm80 INTEGER NOT NULL,
	parent INTEGER NOT NULL
);

CREATE TABLE typing_texts (
	id INTEGER NOT NULL PRIMARY KEY,
	text TEXT NOT NULL
);
